services:
  backend:
    build:
      context: ./backend
      target: base
    container_name: pontocerto-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      redis:
        condition: service_started
    networks:
      - pontocerto-net
    volumes:
      - ./backend/uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 400M # Evitar que o Node consuma toda a RAM da VPS


  redis:
    image: redis:7-alpine
    container_name: pontocerto-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - pontocerto-net
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  pontocerto-net:
    driver: bridge

volumes:
  redis_data:
